const labels = {
  English: { Dashboard:'Dashboard', 'Analyze Requirement':'Analyze Requirement', Recommendations:'Recommendations', 'Compare Standards':'Compare Standards', Compliance:'Compliance', 'Knowledge Graph':'Knowledge Graph', 'AI Assistant':'AI Assistant', 'Tender Documents':'Tender Documents', Reports:'Reports', Alerts:'Alerts', Settings:'Settings', Analyze:'Analyze', Clear:'Clear' },
  'हिन्दी': { Dashboard:'डैशबोर्ड', 'Analyze Requirement':'आवश्यकता विश्लेषण', Recommendations:'सिफारिशें', 'Compare Standards':'मानकों की तुलना', Compliance:'अनुपालन', 'Knowledge Graph':'नॉलेज ग्राफ', 'AI Assistant':'एआई सहायक', 'Tender Documents':'निविदा दस्तावेज़', Reports:'रिपोर्ट', Alerts:'अलर्ट', Settings:'सेटिंग्स', Analyze:'विश्लेषण करें', Clear:'साफ़ करें' },
  'తెలుగు': { Dashboard:'డాష్‌బోర్డ్', 'Analyze Requirement':'అవసర విశ్లేషణ', Recommendations:'సిఫార్సులు', 'Compare Standards':'ప్రమాణాల పోలిక', Compliance:'అనుసరణ', 'Knowledge Graph':'నాలెడ్జ్ గ్రాఫ్', 'AI Assistant':'AI సహాయకుడు', 'Tender Documents':'టెండర్ పత్రాలు', Reports:'రిపోర్టులు', Alerts:'అలర్ట్‌లు', Settings:'సెట్టింగ్స్', Analyze:'విశ్లేషించు', Clear:'క్లియర్' },
  'தமிழ்': { Dashboard:'டாஷ்போர்டு', 'Analyze Requirement':'தேவை பகுப்பாய்வு', Recommendations:'பரிந்துரைகள்', 'Compare Standards':'தரநிலைகளை ஒப்பிடு', Compliance:'இணக்கம்', 'Knowledge Graph':'அறிவு வரைபடம்', 'AI Assistant':'AI உதவியாளர்', 'Tender Documents':'டெண்டர் ஆவணங்கள்', Reports:'அறிக்கைகள்', Alerts:'எச்சரிக்கைகள்', Settings:'அமைப்புகள்', Analyze:'பகுப்பாய்வு', Clear:'அழி' },
  'ಕನ್ನಡ': { Dashboard:'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', 'Analyze Requirement':'ಅವಶ್ಯಕತೆ ವಿಶ್ಲೇಷಣೆ', Recommendations:'ಶಿಫಾರಸುಗಳು', 'Compare Standards':'ಮಾನದಂಡಗಳ ಹೋಲಿಕೆ', Compliance:'ಅನುಸರಣೆ', 'Knowledge Graph':'ಜ್ಞಾನ ಗ್ರಾಫ್', 'AI Assistant':'AI ಸಹಾಯಕ', 'Tender Documents':'ಟೆಂಡರ್ ದಾಖಲೆಗಳು', Reports:'ವರದಿಗಳು', Alerts:'ಎಚ್ಚರಿಕೆಗಳು', Settings:'ಸೆಟ್ಟಿಂಗ್‌ಗಳು', Analyze:'ವಿಶ್ಲೇಷಿಸಿ', Clear:'ಅಳಿಸಿ' },
  'മലയാളം': { Dashboard:'ഡാഷ്ബോർഡ്', 'Analyze Requirement':'ആവശ്യകത വിശകലനം', Recommendations:'ശുപാർശകൾ', 'Compare Standards':'സ്റ്റാൻഡേർഡുകൾ താരതമ്യം', Compliance:'അനുസരണം', 'Knowledge Graph':'നോളജ് ഗ്രാഫ്', 'AI Assistant':'AI സഹായി', 'Tender Documents':'ടെൻഡർ രേഖകൾ', Reports:'റിപ്പോർട്ടുകൾ', Alerts:'അലർട്ടുകൾ', Settings:'ക്രമീകരണങ്ങൾ', Analyze:'വിശകലനം', Clear:'മായ്ക്കുക' },
  'मराठी': { Dashboard:'डॅशबोर्ड', 'Analyze Requirement':'गरज विश्लेषण', Recommendations:'शिफारसी', 'Compare Standards':'मानक तुलना', Compliance:'अनुपालन', 'Knowledge Graph':'नॉलेज ग्राफ', 'AI Assistant':'AI सहाय्यक', 'Tender Documents':'निविदा कागदपत्रे', Reports:'अहवाल', Alerts:'सूचना', Settings:'सेटिंग्ज', Analyze:'विश्लेषण', Clear:'साफ करा' },
  'বাংলা': { Dashboard:'ড্যাশবোর্ড', 'Analyze Requirement':'প্রয়োজন বিশ্লেষণ', Recommendations:'সুপারিশ', 'Compare Standards':'মান তুলনা', Compliance:'সম্মতি', 'Knowledge Graph':'নলেজ গ্রাফ', 'AI Assistant':'AI সহায়ক', 'Tender Documents':'টেন্ডার নথি', Reports:'রিপোর্ট', Alerts:'সতর্কতা', Settings:'সেটিংস', Analyze:'বিশ্লেষণ', Clear:'মুছুন' },
  'ગુજરાતી': { Dashboard:'ડેશબોર્ડ', 'Analyze Requirement':'જરૂરિયાત વિશ્લેષણ', Recommendations:'ભલામણો', 'Compare Standards':'ધોરણોની તુલના', Compliance:'અનુપાલન', 'Knowledge Graph':'નોલેજ ગ્રાફ', 'AI Assistant':'AI સહાયક', 'Tender Documents':'ટેન્ડર દસ્તાવેજો', Reports:'રિપોર્ટ્સ', Alerts:'ચેતવણીઓ', Settings:'સેટિંગ્સ', Analyze:'વિશ્લેષણ', Clear:'સાફ' },
  'ਪੰਜਾਬੀ': { Dashboard:'ਡੈਸ਼ਬੋਰਡ', 'Analyze Requirement':'ਲੋੜ ਵਿਸ਼ਲੇਸ਼ਣ', Recommendations:'ਸਿਫ਼ਾਰਸ਼ਾਂ', 'Compare Standards':'ਮਿਆਰਾਂ ਦੀ ਤੁਲਨਾ', Compliance:'ਪਾਲਣਾ', 'Knowledge Graph':'ਨੋਲੇਜ ਗ੍ਰਾਫ', 'AI Assistant':'AI ਸਹਾਇਕ', 'Tender Documents':'ਟੈਂਡਰ ਦਸਤਾਵੇਜ਼', Reports:'ਰਿਪੋਰਟਾਂ', Alerts:'ਚੇਤਾਵਨੀਆਂ', Settings:'ਸੈਟਿੰਗਾਂ', Analyze:'ਵਿਸ਼ਲੇਸ਼ਣ', Clear:'ਸਾਫ਼' }
};
export const t = (lang, key) => labels[lang]?.[key] || labels.English[key] || key;
export default labels;

export const supportedLanguages=['English','हिन्दी','తెలుగు','தமிழ்','ಕನ್ನಡ','മലയാളം','मराठी','বাংলা','ગુજરાતી','ਪੰਜਾਬੀ','ଓଡ଼ିଆ','অসমীয়া','اردو','संस्कृतम्','कॉशुर','कोंकणी','मैथिली','नेपाली','মৈতৈલোন্','سنڌي','बड़ो','संताली'];
